name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Validar sintaxe do script Bash
        run: bash -n status-check.sh

  test:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Simular execução de testes
        run: |
          echo "Running tests"
          exit 0

  package:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Criar arquivo report.zip
        run: zip report.zip status-check.sh README.md

      - name: Fazer upload do artefato
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.zip
