name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Validar sintaxe do script Bash
        run: |
          bash -n status-check.sh || {
            echo "::error::Falha na validação do script Bash"
            exit 1
          }
          echo "::warning::Sintaxe validada com sucesso"

  test:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Simular execução de testes
        run: |
          echo "Running tests"
          echo "::warning::Teste simulado executado"
          exit 0

  package:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Criar arquivo report.zip
        run: zip report.zip status-check.sh README.md

      - name: Fazer upload do artefato
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.zip

      - name: Criar resumo do job
        run: |
          echo "### Resumo da Build" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Sistema operacional:** $RUNNER_OS" >> $GITHUB_STEP_SUMMARY
          echo "**Branch:** $GITHUB_REF_NAME" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- Validar sintaxe: concluído" >> $GITHUB_STEP_SUMMARY
          echo "- Testes: concluídos" >> $GITHUB_STEP_SUMMARY
          echo "- Artefato: [report.zip](${{ github.server_url }}/${{ github.repository }}/actions/artifacts)" >> $GITHUB_STEP_SUMMARY
